### ISSUE TITLE
Technology Research - Front End

### ISSUE THREAD

**Issue by zhouyiartemiswang** [kbnewlon/project2#17]
Fullpage
- [x] installation
- [x] usage

Slick
- [x] installation
- [x] usage

**Comment by kbnewlon** [comment]
fullPage 
info from their github repo: https://github.com/alvarotrigo/fullpage.js
installation: npm install fullpage.js
usage: 
![image](https://user-images.githubusercontent.com/69712047/96547137-6c6a5380-1260-11eb-914b-bdf08a35a5f4.png)
More research necessary.

**Comment by kbnewlon** [comment]
leaflet
info: https://leafletjs.com/examples/quick-start/
