### ISSUE TITLE
Research resort database

### ISSUE THREAD

**Issue by zhouyiartemiswang** [kbnewlon/project2#4]

**Comment by cmacgeorge1** [comment]
- Mt. Baker Ski Area
Official site: https://www.mtbaker.us/

- The Summit at Snoqualmie
Official site: http://www.summitatsnoqualmie.com/

- Crystal Mountain Resort
Official site: https://crystalmountainresort.com/

- Stevens Pass Resort
Official site: https://www.stevenspass.com/site

- 49 Degrees North Mountain Ski & Snowboard Resort
Official site: http://www.ski49n.com/

- White Pass Ski Area
Official site: http://skiwhitepass.com/

- Mission Ridge Ski & Board Resort
Official site: https://www.missionridge.com/

- Mt. Spokane Ski and Snowboard 
Official site: http://www.mtspokane.com/

- Alpental Ski Resort
Official site: https://summitatsnoqualmie.com/alpental

- Ski Bluewood
Official site: http://www.bluewood.com/

**Comment by cmacgeorge1** [comment]
Possible APIs to use:

SnoCounty Conditions and Profile JSON API
https://feeds.snocountry.net/

Emailed the administrator to see if we can get it for free.

**Comment by cmacgeorge1** [comment]
This is a comprehensive database/API with all information plus some that we were wanting to add to our app. Please take a look and give feedback.

http://docs.clientservice.onthesnow.com/docs/index.html
